# Generated by Django 5.2.7 on 2025-11-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_shortlink'),
        ('user', '0002_favorite_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorites'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart'},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subsctiption',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'follow')},
        ),
    ]
