# Generated by Django 5.2.7 on 2025-11-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_delete_shoppingcart'),
        ('user', '0004_alter_subscription_follow_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'recipe')},
        ),
    ]
