# Generated by Django 5.2.7 on 2025-12-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('recipe', '0014_alter_recipeingredient_options_and_more'),
        ('user', '0005_alter_shoppingcart_unique_together.py'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
