# Generated by Django 5.2.7 on 2025-12-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_shoppingcart_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
    ]
