# Generated by Django 5.2.7 on 2025-11-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_description_recipe_text_remove_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredients'},
        ),
    ]
