# Generated by Django 5.2.7 on 2025-11-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes'},
        ),
    ]
