# Generated by Django 5.2.7 on 2025-11-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
