# Generated by Django 5.2.7 on 2025-11-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_delete_shoppingcart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
