# Generated by Django 5.2.7 on 2025-12-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredients'},
        ),
    ]
